// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://axvfwqqdwnpkboutygln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4dmZ3cXFkd25wa2JvdXR5Z2xuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODk3ODgyNjEsImV4cCI6MjEwNTM2NDI2MX0.7edr9UrlFFhdiEgCCV9bG9iZDqxGt2PKXZOtUF2NKLM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});